sudo: false
language: node_js
env:
    - NODE_ENV=development
cache:
  directories:
    - node_modules
notifications:
  email: false
git:
  depth: 1
node_js:
  - '7'
  - '6'
  - '4'
install:
  - npm install
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
